# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tutoring.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tutoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etutoring.proto\x12\x07idna.v1\"\x1a\n\x0bPingRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1b\n\x0cPingResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2F\n\x0fTutoringService\x12\x33\n\x04Ping\x12\x14.idna.v1.PingRequest\x1a\x15.idna.v1.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tutoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=27
  _globals['_PINGREQUEST']._serialized_end=53
  _globals['_PINGRESPONSE']._serialized_start=55
  _globals['_PINGRESPONSE']._serialized_end=82
  _globals['_TUTORINGSERVICE']._serialized_start=84
  _globals['_TUTORINGSERVICE']._serialized_end=154
# @@protoc_insertion_point(module_scope)
