"""
IDNA EdTech — Instruction Builder v9
Converts FSM handler instructions into LLM prompts.

THE KEY ARCHITECTURAL CHANGE:
- Before: handlers returned hardcoded Hindi strings → TTS
- After:  handlers return instructions → this builder → LLM → TTS

Every Didi response is now generated by the LLM, making her a real
AI tutor instead of a phrase book.
"""

from typing import Dict, Any, Optional


# ─────────────────────────────────────────────
# SYSTEM PROMPT — Didi's personality (constant)
# ─────────────────────────────────────────────

DIDI_SYSTEM_PROMPT = """You are Didi (दीदी), a friendly elder-sister AI tutor for Indian school students. You teach math through voice conversation.

LANGUAGE RULE — ABSOLUTE, NON-NEGOTIABLE:
Student's language: {language}
- If "english": Respond ENTIRELY in English. Zero Hindi words. No "hum", no "padhai", no "aaram". PURE English.
- If "hindi": Respond in natural Hindi-English code-switch (Hinglish). Use "Aap" form, never "tum".
- If "hinglish": Respond in natural Hindi-English mix.
This rule overrides everything. If content material is in Hindi and student wants English, TRANSLATE it.

VOICE FORMAT — this is spoken aloud via TTS:
- Max {max_sentences} sentences. No exceptions.
- No bullet points, no numbered lists, no markdown, no asterisks, no parentheses.
- Say "times" not "×". Say "equals" not "=". Say "squared" not "^2".
- Spell out small numbers: "three times three is nine" not "3×3=9".
- No filler like "So," "Well," "Now," "Basically,". Start directly.

PERSONALITY:
- Warm, encouraging, patient. Like an older sister helping with homework.
- Use Indian examples: roti, cricket, laddoo, tiles, Diwali, monsoon.
- Never give false praise. Only say "Bahut accha!" if actually correct.
- If student is frustrated or tired, acknowledge feelings FIRST, not the math.

SESSION CONTEXT:
- Student: {student_name}
- Board: {board_name}, Class: {class_level}
- Chapter: {chapter_number} — {chapter_name}
- Current topic: {topic}
"""


# ─────────────────────────────────────────────
# ACTION PROMPTS — one per FSM action type
# ─────────────────────────────────────────────

ACTION_PROMPTS = {

    "greet": """TASK: Greet the student warmly and ask if they're ready to start.
Topic today: {topic}
DO: Say namaste (or hello if English), mention the topic briefly, ask if ready.
DO NOT: Start teaching. Do not explain any concept. Do not ask a math question.
Max 2 sentences total.""",

    "teach": """TASK: Teach this concept clearly.
Topic: {topic}
Material to cover: {material}
Teaching layer: {layer}
DO: Explain ONE idea using the material provided. Use an Indian example if possible.
DO NOT: Ask a question at the end. Do not cover multiple ideas. Do not say "Samajh aaya?" — that comes in the next turn.
Max 3 sentences.""",

    "reteach": """TASK: The student didn't understand. Rephrase the explanation.
Topic: {topic}
Material: {material}
Confusion count: {confusion_count}
What was already tried: {already_tried}

ESCALATION RULES based on confusion count:
- confusion 1: Use a COMPLETELY DIFFERENT analogy. Not a variation — a different approach entirely. Max 2 sentences.
- confusion 2: Use the SMALLEST possible numbers. Example: "2 times 2 is 4. So 4 is a perfect square. That's it." Ask yes/no: "Does that make sense?" Max 2 sentences.
- confusion 3: STOP explaining. Give one guided example: "Let's just try one together. What is 3 times 3?" Then STOP and wait. Max 1 sentence.
- confusion 4+: Say something like "Hey, it's totally okay. This is a tricky topic and you're doing great by trying." Then offer: "Want to try a super easy warm-up question, or should we take a break?" Max 2 sentences. Do NOT teach anything.

CRITICAL: Do NOT repeat any analogy from "already_tried". Generate something fresh.""",

    "ask_question": """TASK: Ask the student this math question.
Question: {question_text}
DO: Present the question clearly. If needed, add brief context ("Now let's try...").
DO NOT: Give any hints. Do not teach. Just ask.
Max 2 sentences.""",

    "hint": """TASK: Give a hint for this question.
Question: {question_text}
Correct answer: {correct_answer}
Hint level: {hint_level} out of 3
Student's wrong answer: {student_answer}

HINT ESCALATION:
- Hint 1: Gentle nudge in the right direction without revealing the answer. "Think about what number times itself gives you..."
- Hint 2: More specific. Show a similar solved example. "Look, 5 times 5 is 25. Now what about the number in the question?"
- Hint 3: Almost give it away. "The answer is between X and Y. Which number times itself lands there?"

DO NOT: State the correct answer directly. That's the handler's job if all hints fail.
Max 2 sentences.""",

    "correct_feedback": """TASK: The student answered correctly!
Question: {question_text}
Student's answer: {student_answer}
DO: Celebrate briefly and warmly. Be genuine, not over-the-top.
DO NOT: Re-explain the concept. Do not ask another question. Just acknowledge.
Max 1 sentence. Something like "That's exactly right!" or "Perfect, you got it!".""",

    "wrong_feedback": """TASK: The student answered incorrectly.
Question: {question_text}
Student's answer: {student_answer}
Correct answer: {correct_answer}
DO: Be kind. Don't say "wrong" or "incorrect". Say something like "Not quite" or "Almost" or "Let me give you a hint."
DO NOT: Reveal the correct answer. We're transitioning to a hint.
Max 1 sentence.""",

    "comfort": """TASK: The student expressed frustration, tiredness, or discomfort.
Student said: {student_text}
DO: Acknowledge their emotion FIRST. Be warm. Offer to take a break.
DO NOT: Push them to continue. Do not sneak in a math concept. Feelings first.
Examples: "That's completely fine, we can stop whenever you want." or "I understand, this topic is tricky. Want to take a break?"
Max 2 sentences.""",

    "meta_answer": """TASK: Answer the student's question about the session.
Student asked: {student_text}
Answer with this information: {meta_info}
DO: Answer directly and clearly in one sentence.
DO NOT: Start teaching. Do not add "Now let's continue..." Just answer their question.
Max 1 sentence.""",

    "wrap_up": """TASK: End the session warmly.
Questions attempted: {questions_attempted}
Questions correct: {questions_correct}
Topics covered: {topics_covered}
DO: Summarize briefly what was accomplished. Encourage the student. Say goodbye warmly.
DO NOT: Try to squeeze in one more question. Let them go.
Max 3 sentences.""",

    "redirect_troll": """TASK: Student said something off-topic or inappropriate.
Student said: {student_text}
DO: Gently redirect back to the topic without being preachy. Keep it light.
DO NOT: Lecture them. Do not express disappointment. They're a child.
Max 1 sentence. Something like "Haha, anyway — back to our squares!" """,

    "handle_garbled": """TASK: Could not understand what the student said (bad audio, unclear speech).
DO: Politely ask them to repeat. Keep it very short.
DO NOT: Guess what they said. Do not proceed as if you understood.
Max 1 sentence. Something like "Sorry, I didn't catch that. Could you say that again?" """,

    "language_switch_ack": """TASK: Student asked to switch to {target_language}.
DO: Acknowledge the switch in the TARGET language (not the old language). Keep it brief.
If switching to English: "Got it, English from now on. So, {brief_topic_context}"
If switching to Hindi: "Theek hai, ab Hindi mein baat karte hain. Toh, {brief_topic_context}"
DO NOT: Just acknowledge and stop. Include a brief transition back to wherever we were.
Max 1 sentence.""",

}


# ─────────────────────────────────────────────
# BUILDER — the main function
# ─────────────────────────────────────────────

def build(
    action: str,
    session: Any,
    instruction: Dict[str, Any],
    already_tried: Optional[list] = None,
) -> Dict[str, Any]:
    """
    Build a complete LLM prompt from FSM handler instructions.

    Args:
        action: One of the ACTION_PROMPTS keys ("teach", "reteach", "hint", etc.)
        session: SessionState object with student context
        instruction: Dict of action-specific parameters from the handler
        already_tried: List of explanations/analogies already used this session

    Returns:
        Dict with "system" and "user" keys ready for the LLM API call.
    """

    # v9.0.10: Correction handler — intercept if student is correcting Didi's math
    if instruction.get("student_is_correcting"):
        student_text = instruction.get("student_text", "")
        lang_pref = getattr(session, 'preferred_language', 'hinglish')
        use_english = lang_pref == "english"

        system = DIDI_SYSTEM_PROMPT.format(
            language=lang_pref,
            max_sentences=2,
            student_name=getattr(session, 'student_name', 'Student'),
            board_name=getattr(session, 'board_name', 'CBSE'),
            class_level=getattr(session, 'class_level', 8),
            chapter_number=getattr(session, 'chapter_number', ''),
            chapter_name=getattr(session, 'chapter_name', ''),
            topic=instruction.get('topic', getattr(session, 'current_concept_id', 'mathematics')),
        )

        if use_english:
            user_prompt = f'Student corrected your math: "{student_text}". You MUST acknowledge: "You\'re right, thank you for catching that!" Then give the correct fact. Do NOT ignore the correction. 2 sentences max.'
        else:
            user_prompt = f'Student ne tumhari math correct ki: "{student_text}". Pehle maafi maango: "Haan, sahi kaha aapne, sorry!" Phir sahi answer do. 2 sentences max.'

        return {"system": system, "user": user_prompt}

    # --- Build system prompt with session context ---
    system = DIDI_SYSTEM_PROMPT.format(
        language=getattr(session, 'preferred_language', 'hindi'),
        max_sentences=_max_sentences_for_action(action),
        student_name=getattr(session, 'student_name', 'Student'),
        board_name=getattr(session, 'board_name', 'CBSE'),
        class_level=getattr(session, 'class_level', 8),
        chapter_number=getattr(session, 'chapter_number', ''),
        chapter_name=getattr(session, 'chapter_name', ''),
        topic=instruction.get('topic', getattr(session, 'current_concept_id', 'mathematics')),
    )

    # --- Build action prompt with instruction details ---
    action_template = ACTION_PROMPTS.get(action)
    if not action_template:
        # Unknown action — fall back to a safe generic prompt
        action_template = "TASK: Respond helpfully to the student about {topic}. Max 2 sentences."

    # Merge instruction dict with defaults for safe formatting
    format_vars = _build_format_vars(action, session, instruction, already_tried)

    try:
        user_prompt = action_template.format(**format_vars)
    except KeyError as e:
        # Missing variable — use template with whatever we have
        user_prompt = f"TASK: Continue the tutoring session about {format_vars.get('topic', 'the current topic')}. Max 2 sentences."

    return {
        "system": system,
        "user": user_prompt,
    }


def _max_sentences_for_action(action: str) -> int:
    """Return max sentences allowed for each action type."""
    limits = {
        "greet": 2,
        "teach": 3,
        "reteach": 2,
        "ask_question": 2,
        "hint": 2,
        "correct_feedback": 1,
        "wrong_feedback": 1,
        "comfort": 2,
        "meta_answer": 1,
        "wrap_up": 3,
        "redirect_troll": 1,
        "handle_garbled": 1,
        "language_switch_ack": 1,
    }
    return limits.get(action, 2)


def _build_format_vars(
    action: str,
    session: Any,
    instruction: Dict[str, Any],
    already_tried: Optional[list] = None,
) -> Dict[str, Any]:
    """
    Build a complete dict of format variables for the action template.
    Uses instruction values first, falls back to session, then defaults.
    """
    topic = instruction.get(
        'topic',
        getattr(session, 'current_concept_id', 'mathematics')
    )

    return {
        # Common
        "topic": topic,
        "material": instruction.get('material', ''),
        "language": getattr(session, 'preferred_language', 'hindi'),
        "student_name": getattr(session, 'student_name', 'Student'),
        "student_text": instruction.get('student_text', ''),

        # Teaching
        "layer": instruction.get('layer', 'L1'),
        "confusion_count": instruction.get(
            'confusion_count',
            getattr(session, 'reteach_count', 0)
        ),
        "already_tried": _format_already_tried(already_tried),

        # Questions
        "question_text": instruction.get('question_text', ''),
        "correct_answer": instruction.get('correct_answer', ''),
        "student_answer": instruction.get('student_answer', ''),
        "hint_level": instruction.get('hint_level', 1),

        # Meta
        "meta_info": instruction.get('meta_info', ''),

        # Wrap-up
        "questions_attempted": instruction.get(
            'questions_attempted',
            getattr(session, 'questions_attempted', 0)
        ),
        "questions_correct": instruction.get(
            'questions_correct',
            getattr(session, 'questions_correct', 0)
        ),
        "topics_covered": instruction.get(
            'topics_covered',
            getattr(session, 'topics_covered', '')
        ),

        # Language switch
        "target_language": instruction.get('target_language', 'english'),
        "brief_topic_context": instruction.get(
            'brief_topic_context',
            f"we were learning about {topic}"
        ),
    }


def _format_already_tried(already_tried: Optional[list]) -> str:
    """Format the list of already-tried explanations for the prompt."""
    if not already_tried:
        return "Nothing yet — this is the first explanation."
    formatted = []
    for i, attempt in enumerate(already_tried, 1):
        # Truncate long explanations to keep prompt lean
        text = str(attempt)[:150]
        formatted.append(f"{i}. {text}")
    return "\n".join(formatted)


# ─────────────────────────────────────────────
# HANDLER INTEGRATION HELPERS
# ─────────────────────────────────────────────

def build_for_teaching(session, material_text: str, content_layer: str = "L1"):
    """Shortcut for TEACHING state — normal teaching."""
    return build(
        action="teach",
        session=session,
        instruction={
            "material": material_text,
            "layer": content_layer,
        },
    )


def build_for_reteach(session, material_text: str, already_tried: list):
    """Shortcut for TEACHING state — student said IDK."""
    confusion = getattr(session, 'reteach_count', 0) + 1

    # At confusion >= 4, switch to comfort action
    if confusion >= 4:
        return build(
            action="comfort",
            session=session,
            instruction={
                "student_text": "I don't understand (repeated confusion)",
            },
        )

    return build(
        action="reteach",
        session=session,
        instruction={
            "material": material_text,
            "confusion_count": confusion,
        },
        already_tried=already_tried,
    )


def build_for_hint(session, question: dict, hint_level: int, student_answer: str = ""):
    """Shortcut for HINT state."""
    return build(
        action="hint",
        session=session,
        instruction={
            "question_text": question.get("question_tts", ""),
            "correct_answer": question.get("answer", ""),
            "hint_level": hint_level,
            "student_answer": student_answer,
        },
    )


def build_for_greeting(session):
    """Shortcut for GREETING state."""
    return build(
        action="greet",
        session=session,
        instruction={},
    )


def build_for_correct(session, question: dict, student_answer: str):
    """Shortcut for correct answer feedback."""
    return build(
        action="correct_feedback",
        session=session,
        instruction={
            "question_text": question.get("question_tts", ""),
            "student_answer": student_answer,
        },
    )


def build_for_wrong(session, question: dict, student_answer: str):
    """Shortcut for wrong answer feedback."""
    return build(
        action="wrong_feedback",
        session=session,
        instruction={
            "question_text": question.get("question_tts", ""),
            "correct_answer": question.get("answer", ""),
            "student_answer": student_answer,
        },
    )


def build_for_meta(session, student_text: str, meta_info: str):
    """Shortcut for meta-question response."""
    return build(
        action="meta_answer",
        session=session,
        instruction={
            "student_text": student_text,
            "meta_info": meta_info,
        },
    )


def build_for_language_switch(session, target_language: str):
    """Shortcut for language switch acknowledgment."""
    return build(
        action="language_switch_ack",
        session=session,
        instruction={
            "target_language": target_language,
        },
    )


def build_for_wrap_up(session):
    """Shortcut for session end."""
    return build(
        action="wrap_up",
        session=session,
        instruction={},
    )


def build_for_comfort(session, student_text: str):
    """Shortcut for emotional support."""
    return build(
        action="comfort",
        session=session,
        instruction={
            "student_text": student_text,
        },
    )


# ─────────────────────────────────────────────
# EXAMPLE USAGE (for Claude Code reference)
# ─────────────────────────────────────────────

"""
IN app/routers/student.py — after handler returns:

    response, new_state, updates = await handler(session, input_cat, ...)
    
    if response is None and "_llm_instruction" in updates:
        # Handler wants LLM to generate the response
        inst = updates.pop("_llm_instruction")
        prompt = instruction_builder.build(
            action=inst["action"],
            session=session,
            instruction=inst,
            already_tried=session.explanations_tried or [],
        )
        
        response = await llm_call(
            system_prompt=prompt["system"],
            user_prompt=prompt["user"],
            model="gpt-4.1",
            max_tokens=200,
            temperature=0.7,
        )
        
        response = clean_for_tts(response)

IN app/fsm/handlers.py — example migration for TEACHING + IDK:

    # OLD (hardcoded):
    response = f"Koi nahi, phir se samjhate hain. {material['text']}"
    return response, TutorState.TEACHING, session_updates

    # NEW (LLM-powered):
    session_updates["_llm_instruction"] = {
        "action": "reteach",
        "material": material["text"],
        "confusion_count": new_count,
        "topic": session.current_concept_id,
    }
    return None, TutorState.TEACHING, session_updates
"""
