# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tutoring.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tutoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etutoring.proto\x12\x07idna.v1\";\n\x13StartSessionRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x10\n\x08topic_id\x18\x02 \x01(\t\"`\n\x14StartSessionResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12 \n\x05state\x18\x02 \x01(\x0e\x32\x11.idna.v1.FsmState\x12\x12\n\ntutor_text\x18\x03 \x01(\t\"H\n\x0bTurnRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x11\n\tuser_text\x18\x03 \x01(\t\"\xd7\x01\n\x0cTurnResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12%\n\nnext_state\x18\x02 \x01(\x0e\x32\x11.idna.v1.FsmState\x12\x12\n\ntutor_text\x18\x03 \x01(\t\x12\x15\n\rattempt_count\x18\x04 \x01(\x05\x12\x1b\n\x13\x66rustration_counter\x18\x05 \x01(\x05\x12\x0e\n\x06intent\x18\x06 \x01(\t\x12\x10\n\x08topic_id\x18\x07 \x01(\t\x12\x13\n\x0bquestion_id\x18\x08 \x01(\t\x12\r\n\x05title\x18\t \x01(\t*Z\n\x08\x46smState\x12\x13\n\x0f\x46SM_UNSPECIFIED\x10\x00\x12\x0b\n\x07\x45XPLAIN\x10\x01\x12\x08\n\x04QUIZ\x10\x02\x12\x0c\n\x08\x45VALUATE\x10\x03\x12\x08\n\x04HINT\x10\x04\x12\n\n\x06REVEAL\x10\x05\x32\x93\x01\n\x0fTutoringService\x12K\n\x0cStartSession\x12\x1c.idna.v1.StartSessionRequest\x1a\x1d.idna.v1.StartSessionResponse\x12\x33\n\x04Turn\x12\x14.idna.v1.TurnRequest\x1a\x15.idna.v1.TurnResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tutoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FSMSTATE']._serialized_start=478
  _globals['_FSMSTATE']._serialized_end=568
  _globals['_STARTSESSIONREQUEST']._serialized_start=27
  _globals['_STARTSESSIONREQUEST']._serialized_end=86
  _globals['_STARTSESSIONRESPONSE']._serialized_start=88
  _globals['_STARTSESSIONRESPONSE']._serialized_end=184
  _globals['_TURNREQUEST']._serialized_start=186
  _globals['_TURNREQUEST']._serialized_end=258
  _globals['_TURNRESPONSE']._serialized_start=261
  _globals['_TURNRESPONSE']._serialized_end=476
  _globals['_TUTORINGSERVICE']._serialized_start=571
  _globals['_TUTORINGSERVICE']._serialized_end=718
# @@protoc_insertion_point(module_scope)
